name: CI for docker image built from local source code

on:
  workflow_dispatch:


env:
  APISIX_IMAGE_TAG: "local-debian-dev"
  APISIX_VERSION: "local"

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - debian

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          cd debian-dev && \
          git clone https://github.com/arbor-95/local-apisix.git && \
          docker build -t ${APISIX_IMAGE_TAG} --build-arg CODE_PATH=./local-apisix -f ./Dockerfile.local .