name: test

on:
  workflow_dispatch:
env:
  APISIX_IMAGE_TAG: nginx:latest

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - debian

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker pull nginx

      - name: Save Images Local
        run: |
          docker save nginx:latest > nginx.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${APISIX_IMAGE_TAG}
          path: nginx.tar
          retention-days: 1
